;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   jue. ago. 6 2020
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
        ; Write your code here
ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START